# Copyright 2019 Wirepas Ltd

version: '2'
services:
    backend-client:
        container_name: wm-backend-client
        image: wirepas/backend-client:latest
        build:
            dockerfile: container/slim/Dockerfile
            context: ../

        user: wirepas
        working_dir: /home/wirepas/
        stdin_open: true
        tty: true

        restart: always
        network_mode: host

        # from v1.2.0 you can define your settings under
        # the environment key or under a env_file key.
        # If you do that, you can drop the volumes
        environment:
            - WM_DEBUG_LEVEL=info
            - PYTHONUNBUFFERED=true

        # .settings.yml must be located next to this file
        volumes:
            - ./../examples/settings.yml:/home/wirepas/backend-client/vars/settings.yml

        logging:
            driver: json-file
            options:
                max-size: "10M"

        command: ["python",
                  ".local/wirepas_backend_client-extras/examples/mqtt_viewer.py",
                  "--settings",
                  "/home/wirepas/backend-client/vars/settings.yml"]
