# Copyright 2019 Wirepas Ltd

version: '2'
services:
  backend-client:
    restart: always
    image: wirepas/backend-client:latest
    build:
      dockerfile: container/Dockerfile
      context: ../
    network_mode: host

    environment:
      - WM_DEBUG_LEVEL=info
      - PYTHONUNBUFFERED=true

    volumes:
      - ./.settings.yml:/home/wirepas/vars/settings.yml

    command: python examples/mqtt_viewer.py --settings /home/wirepas/vars/settings.yml
