language: python
python:
  - "3.7"

services:
  - docker

dist: "bionic"
jobs:

install:
  - "./.ci/install-devtools.sh"
  - sudo gem install github_changelog_generator
  - pip3 install -r dev-requirements.txt
  - pip3 install -r docs/requirements.txt
  - pip3 install -r requirements.txt
  - pip3 install .

script:
  - "./.ci/style-check.sh"
  - "./.ci/build.sh"
  - WM_BACKEND_CLI_CMD="python -m wirepas_backend_client.test.kpi_mesh" timeout --preserve-status 120 docker-compose -f tests/services/docker-compose.yml up
  - ./.ci/releases.sh
  - source releases.env

deploy:
- provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    - "${TRAVIS_BUILD_DIR}/dist/*"
    - "${TRAVIS_BUILD_DIR}/CHANGELOG.md"
  skip_cleanup: true
  draft: ${GH_RELEASE_DRAFT} = true
  name: ${GH_RELEASE_NAME}
  body: ${GH_RELEASE_BODY}
  prerelease: ${GH_RELEASE_CANDIDATE}
  on:
    tags: true
    branch: master

- provider: script
  script: bash .ci/deploy-pypi.sh ${TRAVIS_BUILD_DIR}/dist/${PYTHON_PKG_NAME}*
  skip_cleanup: true
  on:
    tags: true
    branch: master

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PYTHON_PKG_PATH=.
    - PYTHON_PKG_NAME=wirepas_backend_client
